# Generated by Django 5.1.5 on 2025-01-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created_at',
        ),
    ]
