# Generated by Django 5.1.5 on 2025-01-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_post_content_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
