# Generated by Django 5.1.5 on 2025-01-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_follownotification'),
        ('user', '0002_alter_post_content_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='follownotification',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follownotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_notifications', to='user.post'),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_like_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likenotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_like_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postnotification',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='user.post'),
        ),
        migrations.AlterField(
            model_name='postnotification',
            name='recipients',
            field=models.ManyToManyField(related_name='post_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='user.post')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_comment_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
